name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
        #1
      - name: Checkout repository
        uses: actions/checkout@v4
        #2
      - name: Install pnpm and build project
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
        #3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        #4
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/KamiNuke/kpz-front
